
spring:
  application:
    name: load-test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
